- name: Ensure /srv/compose/mariadb exists
  become: true
  ansible.builtin.file:
    path: /srv/compose/mariadb
    state: directory
    owner: root
    group: root
    mode: "0600"

- name: Ensure Docker network mariadb exists
  become: true
  community.docker.docker_network:
    name: mariadb
    appends: true
    state: present

- name: Template MariaDB docker-compose.yml to server
  become: true
  ansible.builtin.template:
    src: ../../../../docker-compose/mariadb/docker-compose-template.yml
    dest: /srv/compose/mariadb/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Ensure MariaDB is started
  become: true
  community.docker.docker_compose_v2:
    project_src: /srv/compose/mariadb/
    state: present # equivalent to docker compose up
