services:
  db:
    image: postgres
    container_name: postgresql-system
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "{{ lookup('ansible.builtin.password', 'credentials/postgresql_postgres', length=64, chars=['ascii_leters', 'digits']) }}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

volumes:
  pgdata:

networks:
  postgresql:
    external: true