- name: Ensure OpenSSH is installed
  become: true
  community.general.apk:
    name: openssh
    state: present
    update_cache: true

- name: Apply Mozilla recommended SSH config
  become: true
  ansible.builtin.copy:
    content: |
      #########################################################################################################
      # start settings from https://infosec.mozilla.org/guidelines/openssh#modern-openssh-67 as of 2024-12-09 #
      #########################################################################################################

      # Supported HostKey algorithms by order of preference.
      HostKey /etc/ssh/ssh_host_ed25519_key
      HostKey /etc/ssh/ssh_host_rsa_key
      HostKey /etc/ssh/ssh_host_ecdsa_key

      KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256

      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com

      # Password based logins are disabled - only public key based logins are allowed.
      AuthenticationMethods publickey

      # LogLevel VERBOSE logs user's key fingerprint on login. Needed to have a clear audit track of which key was using to log in.
      LogLevel VERBOSE

      # Log sftp level file access (read/write/etc.) that would not be easily logged otherwise.
      Subsystem sftp  /usr/lib/ssh/sftp-server -f AUTHPRIV -l INFO

      # Root login is not allowed for auditing reasons. This is because it's difficult to track which process belongs to which root user:
      #
      # On Linux, user sessions are tracking using a kernel-side session id, however, this session id is not recorded by OpenSSH.
      # Additionally, only tools such as systemd and auditd record the process session id.
      # On other OSes, the user session id is not necessarily recorded at all kernel-side.
      # Using regular users in combination with /bin/su or /usr/bin/sudo ensure a clear audit track.
      PermitRootLogin No

      #######################################################################################################
      # end settings from https://infosec.mozilla.org/guidelines/openssh#modern-openssh-67 as of 2024-12-09 #
      #######################################################################################################

      # Don't let users set environment variables
      PermitUserEnvironment no

      # Only use SSH v2 protocol
      Protocol 2

      # Disable all forwarding
      X11Forwarding no
      AllowTcpForwarding no
      AllowStreamLocalForwarding no
      GatewayPorts no
      PermitTunnel no

      # Disallow login for accounts with empty passwords
      PermitEmptyPasswords no

      # Ignore .rhosts and .shosts
      IgnoreRhosts yes

      # Verify hostname matches IP
      UseDNS yes

      # Don't allow .rhosts or /etc/hosts.equiv
      HostbasedAuthentication no

      # Allow only users with "sshusers" group to login via SSH
      AllowGroups sshusers

      # limit open sessions
      MaxSessions 3

    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  notify: Restart sshd

- name: Remove short Diffie-Hellman moduli # noqa no-changed-when
  become: true
  ansible.builtin.shell: |
    set -o pipefail && awk '$5 >= 3071' /etc/ssh/moduli | tee /etc/ssh/moduli.tmp
    mv /etc/ssh/moduli.tmp /etc/ssh/moduli
  notify: Restart sshd
