- name: Ensure /srv/compose/traefik exists
  become: true
  ansible.builtin.file:
    path: /srv/compose/traefik
    state: directory
    mode: "0644"

- name: Ensure Docker network rev_proxy exists
  become: true
  community.docker.docker_network:
    name: rev_proxy
    appends: true
    state: present

- name: Copy Traefik docker-compose.yml to server
  become: true
  ansible.builtin.copy:
    src: ../../../../docker-compose/traefik/docker-compose.yml
    dest: /srv/compose/traefik/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Ensure Traefik is started
  become: true
  community.docker.docker_compose_v2:
    project_src: /srv/compose/traefik/
    state: present # equivalent to docker compose up
