version: "2.1"

services:
    cms-db:
        image: mysql:8.0
        volumes:
            - "db:/var/lib/mysql:Z"
        environment:
            - MYSQL_DATABASE=cms
            - MYSQL_USER=cms
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        mem_limit: 1g
        env_file: config.env
        restart: always
    cms-xmr:
        image: ghcr.io/xibosignage/xibo-xmr:1.0
        ports:
            - "9505:9505"
        restart: always
        mem_limit: 256m
        env_file: config.env
    cms-web:
        image: ghcr.io/xibosignage/xibo-cms:release-4.2.2
        volumes:
            - "cms-custom:/var/www/cms/custom:Z"
            - "backup:/var/www/backup:Z"
            - "cms-theme-custom:/var/www/cms/web/theme/custom:Z"
            - "cms-library:/var/www/cms/library:Z"
            - "cms-web-userscripts:/var/www/cms/web/userscripts:Z"
            - "cms-ca-certs:/var/www/cms/ca-certs:Z"
        restart: always
        environment:
            - MYSQL_HOST=cms-db
            - XMR_HOST=cms-xmr
            - CMS_USE_MEMCACHED=true
            - MEMCACHED_HOST=cms-memcached
        env_file: config.env
        ports:
            - "8004:80"
        mem_limit: 1g
    cms-memcached:
        image: memcached:alpine
        command: memcached -m 15
        restart: always
        mem_limit: 100M
    cms-quickchart:
      image: ianw/quickchart
      restart: always

volumes:
  backup:
  cms-ca-certs:
  cms-custom:
  cms-library:
  cms-theme-custom:
  cms-web-userscripts:
  db:
