- name: Run update-extlinux
  become: true
  ansible.builtin.command: update-extlinux
  changed_when: true # update-extlinux always updates the syslinux config, we also wouldn't even be calling this handler if nothing changed

- name: Reboot alert
  ansible.builtin.pause: # We want the user to acknowledge this alert explicitly
    prompt: |
      ············································································

        Some implemented measures require a system reboot!
        Please, make sure to reboot the system after playbook execution is done!

      ············································································

- name: Reload sysctl
  become: true
  ansible.builtin.command: sysctl -p
  changed_when: true # always reloads the sysctl config, we also wouldn't even be calling this handler if nothing changed

- name: Remount opt
  become: true
  ansible.posix.mount:
    path: /opt
    state: remounted

- name: Remount tmp
  become: true
  ansible.posix.mount:
    path: /tmp
    state: remounted

- name: Remount srv
  become: true
  ansible.posix.mount:
    path: /srv
    state: remounted

- name: Remount home
  become: true
  ansible.posix.mount:
    path: /home
    state: remounted

- name: Remount usr
  become: true
  ansible.posix.mount:
    path: /usr
    state: remounted

- name: Remount var
  become: true
  ansible.posix.mount:
    path: /usr
    state: remounted
