services:
  db:
    image: mariadb:lts
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "{{ mariadb_root_password }}"
      MARIADB_AUTO_UPGRADE: true
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - mariadb
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mariadb:

networks:
  mariadb:
    external: true
