- name: Ensure rclone and restic is installed
  become: true
  community.general.apk:
    name:
      - rclone
    state: present
    update_cache: true

- name: Check if the rclone repo "remote_bak" already exists
  become: true
  ansible.builtin.command: "rclone ls remote_bak:"
  register: rclone_list_remote_bak
  changed_when: false # never changes anything
  # rclone returns code 1 when the repo does not exist, which would cause Ansible to stop execution
  ignore_errors: true 

- name: Wait for user to configure remote_bak repo
  ansible.builtin.pause:
    prompt: |
      ·······················································

        Manual intervention required!

        Please set up the remote_bak rclone repo with

        rclone config

        For more info, see docs at https://rclone.org/drive/
          
      ·······················································
  when: rclone_list_remote_bak.rc == 1
