- name: "[R5] Configuring a password on the bootloader"
  ansible.builtin.lineinfile:
    path: /etc/update-extlinux.conf
    regexp: "^(password=)"
    line: 'password="$6$ZL32zaE7f9GonTlT$3MwnUsZqEQkrmJUbDJhKwNHxIkq2Fio9W3bemBLRg3ukZ46/j3WWhMbjh4KWVGYvSN0oI6iLP5XLquNhU4cbs0"'
  notify: update-extlinux

- name: "[R8] Configuring the memory options"
  ansible.builtin.lineinfile:
    path: /etc/update-extlinux.conf
    regexp: "^(default_kernel_opts=).*"
    line: 'default_kernel_opts="quiet rootfstype=ext4 page_poison=on pti=on slab_nomerge=yes slub_debug=FZP spec_store_bypass_disable=seccomp spectre_v2=on mce=0 page_alloc.shuffle=1"'
  notify: update-extlinux
    