- name: Ensure /srv/compose/postgresql exists
  become: true
  ansible.builtin.file:
    path: /srv/compose/postgresql
    state: directory
    owner: root
    group: root
    mode: "0600"

- name: Ensure Docker network postgresql exists
  become: true
  community.docker.docker_network:
    name: postgresql
    appends: true
    state: present

- name: Template PostgreSQL docker-compose.yml to server
  become: true
  ansible.builtin.template:
    src: ../../../../docker-compose/postgresql/docker-compose-template.yml
    dest: /srv/compose/postgresql/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Ensure PostgreSQL is started
  become: true
  community.docker.docker_compose_v2:
    project_src: /srv/compose/postgresql/
    state: present # equivalent to docker compose up
